version: '2.1'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - './drive:/var/opt/mssql'

  web:
    build:
      context: ./docker/web/
      dockerfile: Dockerfile
    user: root
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - .:/code/
    ports:
      - "8080:8000"
    environment:
      DJANGO_SETTINGS_MODULE: SqlServerOnDocker.settings
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.example.com

networks:
  mynetwork:
    driver: bridge
volumes:
    database-data: