# Generated by Django 2.2 on 2021-12-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=4000)),
            ],
        ),
    ]
