# Generated by Django 2.2 on 2021-12-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('c_name', models.CharField(max_length=4000)),
                ('mid', models.IntegerField()),
            ],
        ),
    ]
