# Generated by Django 2.2 on 2021-12-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('title', models.CharField(max_length=4000)),
                ('types', models.CharField(max_length=4000)),
                ('years', models.CharField(max_length=4000)),
                ('country', models.CharField(max_length=4000)),
                ('actor', models.CharField(max_length=4000)),
                ('director', models.CharField(max_length=4000)),
                ('m_intro', models.CharField(max_length=4000)),
                ('poster', models.CharField(max_length=4000)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
